# sklearn Clustering - 군집분석 정리
# 실습용 데이터 설정

> ## 1) Import Packages

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

> ## 2) Load Dataset

- Load iris Dataset

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()

- pandas DataFramd

In [ ]:
df = pd.DataFrame(data = iris.data,
                  columns = ['sepal_lengh',
                             'sepal_width',
                             'petal_length',
                             'petal_width'])
df.head()

sepal_lengh  sepal_width  petal_length  petal_width
0          5.1          3.5           1.4          0.2
1          4.9          3.0           1.4          0.2
2          4.7          3.2           1.3          0.2
3          4.6          3.1           1.5          0.2
4          5.0          3.6           1.4          0.2

# 1. K-means

> ## 1) Modeling

In [ ]:
from sklearn.cluster import KMeans
kmeans_3 = KMeans(n_clusters = 3,
                  init = 'k-means++',
                  max_iter = 15,
                  random_state =2045) 
kmeans_3.fit(df)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=15,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=2045, tol=0.0001, verbose=0)

> ## 2) 군집결과

In [ ]:
df['kmeans'] = kmeans_3.labels_
df['target'] = iris.target

In [ ]:
df.groupby('target')['kmeans'].value_counts()

target  kmeans
0       1         50
1       0         48
        2          2
2       2         36
        0         14
Name: kmeans, dtype: int64

# 2. Mean Shift(평균 이동)

- 데이터의 분포를 이용하여 군집의 중심을 탐색
   - 데이터 밀도가 가장 높은 곳으로 중심을 지속적으로 이동

- 군집의 중심점은 데이터포인트가 모여있는 곳이라는 가정
   - 확률 밀도 함수(Probability Desity Function)
   - KDE(Kernel Density Estimation)

> ## 1) Modeling

- Hyperparameter
   - bandwidth : 대역폭이 클수록 적은 수의 군집중심을 가짐

In [ ]:
from sklearn.cluster import MeanShift
meanshift = MeanShift(bandwidth = 0.86)
meanshift.fit_predict(iris.data)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0])

In [ ]:
from sklearn.cluster import estimate_bandwidth
estimate_bandwidth(iris.data)

1.2020768127998687

> ## 2) 군집결과

In [ ]:
df['meanshift'] = meanshift.fit_predict(iris.data)

In [ ]:
df.groupby('target')['meanshift'].value_counts()
# 군집1과 2를 2개, 14개 틀리게 분류

target  meanshift
0       1            50
1       0            48
        1             1
        2             1
2       2            36
        0            14
Name: meanshift, dtype: int64

# 3. GMM(Gaussian Mixture Model)

- 데이터가 여러 개의 가우시안 분포(Gaussian Distribution)(=정규분포)를 가진 데이터들의 집합이라고 가정
   - 개별 정규분포의 모수(평균, 분산)추정
   - 각 데이터포인트가 어떤 정규분포에 해당하는지 확률 추정
      - EM(Expectation and Maximization)

> ## 1) Modeling

In [ ]:
from sklearn.mixture import GaussianMixture
gmm = GaussianMixture(n_components = 3, 
                      random_state = 2045)
gmm.fit(iris.data)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
                means_init=None, n_components=3, n_init=1, precisions_init=None,
                random_state=2045, reg_covar=1e-06, tol=0.001, verbose=0,
                verbose_interval=10, warm_start=False, weights_init=None)

In [ ]:
gmm.predict(iris.data)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

> ## 2) 군집결과

In [ ]:
df['gmm'] = gmm.predict(iris.data)

In [ ]:
df.groupby('target')['gmm'].value_counts()
# 군집1을 5개 틀리게 분류

target  gmm
0       1      50
1       0      45
        2       5
2       2      50
Name: gmm, dtype: int64

# 4. DBSCAN(Density Based Spatial Clustering of Applications with Noise)

- 밀도(Density) 기반 군집
   - 기하학적으로 복잡한 데이터에도 효과적으로 군집 가능
   - 핵심 포인트(Core Point)들을 서로 연결하면서 군집화

> ## 1) Modeling

- Hyperparameter
   - epsilon(esp, 입실론 주변 영역)
      - 입실론 = 반지름
      - 개별 데이터포인트를 중심으로 '입실론 반경'을 가지는 주변 영역
      - 'Core Point' 기준
  - min point(min_samples, 최소 데이터 개수)
     - 개별 데이터포인트의 '입실론 주변 영역'에 포함되는 다른 데이터포인트의 개수
     - 조건 만족시 'Core Point'로 지정

In [ ]:
from sklearn.cluster import DBSCAN
dbscan = DBSCAN(eps = 0.8,
                min_samples = 8,
                metric = 'euclidean')
dbscan.fit_predict(iris.data)
# 음수값이 나옴
# eps가 너무 크면 군집 하나를 묶는 기준이 헐랭해지기 때문에 전체 데이터를 하나의 군집으로 인식할 수 있음

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

> ## 2) 군집결과

In [ ]:
df['dbscan'] = dbscan.fit_predict(iris.data)

In [ ]:
df.groupby('target')['dbscan'].value_counts()
# 2군집은 분류 3개 틀림

target  dbscan
0        0        50
1        1        50
2        1        47
        -1         3
Name: dbscan, dtype: int64

###
#The End
###